version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: /tmp/workspace

    steps:
      - checkout

      # Check if Docker is installed
      - run:
          name: Check if Docker is installed
          command: |
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed. Installing Docker..."
              # Install Docker
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
              # Start Docker
              sudo service docker start
            fi

      # Start Docker and wait for the daemon to be ready
      - run:
          name: Start Docker and wait for the daemon
          command: |
            until docker info &>/dev/null; do
              echo "Waiting for Docker to start..."
              sleep 1
            done

      # Clone the repository and prepare Odoo
      - run:
          name: Clone Repository and Prepare Odoo
          command: |
            ./run.sh /tmp/workspace/mikeintosh_emr 10017 20017

      # Build and run tests if applicable
      # Add your test steps here if needed

      # Deploy the application
      - deploy:
          name: Deploy Odoo
          command: |
            docker-compose -f /tmp/workspace/mikeintosh_emr/docker-compose.yml up -d

      # Output information about the deployment
      - run:
          name: Display Deployment Information
          command: |
            echo 'Started Odoo @ http://localhost:10017 | Master Password: momonahealthcare | Live chat port: 20017'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
