version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: /tmp/workspace

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker:
          version: 20.10.7

      # Clone the repository and prepare Odoo
      - run:
          name: Clone Repository and Prepare Odoo
          command: |
            chmod +x run.sh  # Ensure the script has execute permissions
            ./run.sh /tmp/workspace/mikeintosh_emr 10017 20017

      # Build and run tests if applicable
      # Add your test steps here if needed

      # Deploy the application
      - deploy:
          name: Deploy Odoo
          command: |
            docker-compose -f /tmp/workspace/mikeintosh_emr/docker-compose.yml up -d

      # Output information about the deployment
      - run:
          name: Display Deployment Information
          command: |
            echo 'Started Odoo @ http://localhost:10017 | Master Password: momonahealthcare | Live chat port: 20017'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
